import type { Metadata } from "next";
import type { ReactNode } from "react";

import { Geist_Mono, Montserrat } from "next/font/google";

import "./globals.css";

import Navbar from "@/components/navbar";

const montserrat = Montserrat({
    subsets: ["latin"],
    weight: ["300", "400", "500", "700", "900"],
    variable: "--font-montserrat",
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Uai em Doobro",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: ReactNode;
}) {
    return (
        <html
            lang="pt-BR"
            className={`${montserrat.variable} ${geistMono.variable} h-full antialiased`}
        >
            <body className={`${montserrat.className} min-h-full flex flex-col`}>
                <Navbar />
                {children}
            </body>
        </html>
    );
}